classification: electronic
color: ''
description_extra: surface_mount_right_angle
description_main: 33_pin
id: electronic_header_2_54_mm_33_pin_surface_mount_right_angle
manufacturer: ''
part_number: ''
size: 2_54_mm
type: header
