classification: electronic
color: basic
description_extra: through_hole_right_angle
description_main: single
id: electronic_header_oobb_basic_single_through_hole_right_angle
manufacturer: ''
part_number: ''
size: oobb
type: header
