classification: electronic
color: ''
description_extra: through_hole_long
description_main: 29_pin
id: electronic_header_2_54_mm_29_pin_through_hole_long
manufacturer: ''
part_number: ''
size: 2_54_mm
type: header
