classification: electronic
color: converter
description_extra: ''
description_main: usb_to_serial_converter
id: electronic_ic_sop_16_converter_usb_to_serial_converter_wch_ch340g
manufacturer: wch
part_number: ch340g
size: sop_16
type: ic
