classification: electronic
color: ''
description_extra: surface_mount
description_main: 12_pin
id: electronic_header_2_54_mm_12_pin_surface_mount
manufacturer: ''
part_number: ''
size: 2_54_mm
type: header
