classification: electronic
color: ''
description_extra: surface_mount
description_main: 2x2_4_pin
id: electronic_header_2_54_mm_dual_row_2x2_4_pin_surface_mount
manufacturer: ''
part_number: ''
size: 2_54_mm_dual_row
type: header
