classification: electronic
color: linear
description_extra: 3_3_volt
description_main: '1117'
id: electronic_pmic_sot_223_linear_1117_3_3_volt
manufacturer: ''
part_number: ''
size: sot_223
type: pmic
