classification: electronic
color: ''
description_extra: package_marking_b2
description_main: ''
id: electronic_diode_schottky_sod_123_package_marking_b2_mbr0520
manufacturer: ''
part_number: mbr0520
size: sod_123
type: diode_schottky
