classification: electronic
color: ''
description_extra: through_hole
description_main: 2x36_72_pin
id: electronic_header_2_54_mm_dual_row_2x36_72_pin_through_hole
manufacturer: ''
part_number: ''
size: 2_54_mm_dual_row
type: header
