classification: electronic
color: converter
description_extra: ''
description_main: usb_to_serial_converter
id: electronic_ic_msop_10_converter_usb_to_serial_converter_wch_ch340x
manufacturer: wch
part_number: ch340x
size: msop_10
type: ic
