classification: electronic
color: ''
description_extra: arduino_compatible
description_main: atmega328p
id: electronic_breakout_board_mcu_shennie_atmega328p_arduino_compatible
manufacturer: ''
part_number: ''
size: shennie
type: breakout_board_mcu
