classification: electronic
color: ''
description_extra: surface_mount
description_main: 8_pin
id: electronic_header_2_5_mm_jst_xh_8_pin_surface_mount
manufacturer: ''
part_number: ''
size: 2_5_mm_jst_xh
type: header
