classification: electronic
color: ''
description_extra: through_hole_right_angle
description_main: 3x2_6_pin
id: electronic_header_2_54_mm_triple_row_3x2_6_pin_through_hole_right_angle
manufacturer: ''
part_number: ''
size: 2_54_mm_triple_row
type: header
