classification: electronic
color: ''
description_extra: surface_mount_right_angle
description_main: 2x18_36_pin
id: electronic_header_2_54_mm_dual_row_2x18_36_pin_surface_mount_right_angle
manufacturer: ''
part_number: ''
size: 2_54_mm_dual_row
type: header
