classification: electronic
color: surface_mount
description_extra: ''
description_main: single_pole_double_throw
id: electronic_switch_slide_2_8_mm_x_8_mm_x_1_4_mm_surface_mount_single_pole_double_throw
manufacturer: ''
part_number: ''
size: 2_8_mm_x_8_mm_x_1_4_mm
type: switch_slide
