classification: electronic
color: mcu
description_extra: ''
description_main: atmega328
id: electronic_ic_vqfn_28_mcu_atmega328_microchip_atmega328p_mmh
manufacturer: microchip
part_number: atmega328p_mmh
size: vqfn_28
type: ic
