classification: electronic
color: black
description_extra: dupont
description_main: 6_pin
id: electronic_crimp_housing_2_54_mm_black_6_pin_dupont
manufacturer: ''
part_number: ''
size: 2_54_mm
type: crimp_housing
