classification: electronic
color: ''
description_extra: ''
description_main: ''
id: electronic_prototyping_breadboard_400_point
manufacturer: ''
part_number: ''
size: 400_point
type: prototyping_breadboard
