classification: electronic
color: ''
description_extra: through_hole_long
description_main: 11_pin
id: electronic_socket_2_54_mm_11_pin_through_hole_long
manufacturer: ''
part_number: ''
size: 2_54_mm
type: socket
