classification: electronic
color: converter
description_extra: ''
description_main: usb_to_serial_converter
id: electronic_ic_essop_10_converter_usb_to_serial_converter_wch_ch340k
manufacturer: wch
part_number: ch340k
size: essop_10
type: ic
