classification: electronic
color: ''
description_extra: ''
description_main: 220_ohm
id: electronic_resistor_quarter_watt_through_hole_220_ohm
manufacturer: ''
part_number: ''
size: quarter_watt_through_hole
type: resistor
