classification: electronic
color: basic
description_extra: through_hole_right_angle
description_main: double
id: electronic_header_oobb_basic_double_through_hole_right_angle
manufacturer: ''
part_number: ''
size: oobb
type: header
