classification: electronic
color: surface_mount
description_extra: ''
description_main: single_pole_double_throw
id: electronic_switch_slide_2_54_header_surface_mount_single_pole_double_throw
manufacturer: ''
part_number: ''
size: 2_54_header
type: switch_slide
