classification: electronic
color: multiplexer
description_extra: ''
description_main: power_multiplexer
id: electronic_ic_tssop_8_multiplexer_power_multiplexer_texas_instruments_tps2113apw
manufacturer: texas_instruments
part_number: tps2113apw
size: tssop_8
type: ic
