classification: electronic
color: surface_mount
description_extra: ''
description_main: ''
id: electronic_button_3_5_mm_x_6_mm_x_2_5_mm_surface_mount
manufacturer: ''
part_number: ''
size: 3_5_mm_x_6_mm_x_2_5_mm
type: button
