classification: electronic
color: ''
description_extra: ''
description_main: stepper_motor
id: electronic_breakout_board_motor_driver_step_stick_stepper_motor
manufacturer: ''
part_number: ''
size: step_stick
type: breakout_board_motor_driver
