classification: electronic
color: i2c
description_extra: through_hole_right_angle
description_main: single
id: electronic_header_oobb_i2c_single_through_hole_right_angle
manufacturer: ''
part_number: ''
size: oobb
type: header
