classification: electronic
color: ''
description_extra: ''
description_main: espressif_esp32
id: electronic_breakout_board_mcu_devkitc_espressif_esp32
manufacturer: ''
part_number: ''
size: devkitc
type: breakout_board_mcu
