classification: electronic
color: ''
description_extra: through_hole
description_main: 37_pin
id: electronic_header_2_54_mm_37_pin_through_hole
manufacturer: ''
part_number: ''
size: 2_54_mm
type: header
