classification: electronic
color: basic
description_extra: through_hole_right_angle
description_main: triple
id: electronic_header_oobb_basic_triple_through_hole_right_angle
manufacturer: ''
part_number: ''
size: oobb
type: header
