classification: electronic
color: multiplexer
description_extra: two_to_one
description_main: usb_multiplexer
id: electronic_ic_msop_10_multiplexer_usb_multiplexer_two_to_one_jiangsu_runic_tech_rs2227xn
manufacturer: jiangsu_runic_tech
part_number: rs2227xn
size: msop_10
type: ic
