classification: electronic
color: ''
description_extra: surface_mount
description_main: 10_pin
id: electronic_header_1_mm_jst_sh_10_pin_surface_mount
manufacturer: ''
part_number: ''
size: 1_mm_jst_sh
type: header
