classification: electronic
color: orange
description_extra: ''
description_main: 8_mm_length
id: electronic_crimp_bootlace_ferrule_0_55_mm_diameter_wire_orange_8_mm_length
manufacturer: ''
part_number: ''
size: 0_55_mm_diameter_wire
type: crimp_bootlace_ferrule
