classification: electronic
color: ''
description_extra: surface_mount_right_angle
description_main: 2_pin
id: electronic_header_1_mm_jst_sh_2_pin_surface_mount_right_angle
manufacturer: ''
part_number: ''
size: 1_mm_jst_sh
type: header
