classification: electronic
color: ''
description_extra: surface_mount
description_main: 2x3_6_pin
id: electronic_socket_2_54_mm_dual_row_2x3_6_pin_surface_mount
manufacturer: ''
part_number: ''
size: 2_54_mm_dual_row
type: socket
