classification: electronic
color: mcu
description_extra: ''
description_main: atmega328
id: electronic_ic_dip_28_mcu_atmega328_microchip_atmega328p_pu
manufacturer: microchip
part_number: atmega328p_pu
size: dip_28
type: ic
