classification: electronic
color: ''
description_extra: landing
description_main: i2c
id: electronic_interposer_soic_14_wide_i2c_landing
manufacturer: ''
part_number: ''
size: soic_14_wide
type: interposer
