classification: electronic
color: ''
description_extra: through_hole_short
description_main: 12_pin
id: electronic_header_2_54_mm_12_pin_through_hole_short
manufacturer: ''
part_number: ''
size: 2_54_mm
type: header
