classification: electronic
color: ''
description_extra: through_hole
description_main: 13_pin
id: electronic_socket_2_54_mm_13_pin_through_hole
manufacturer: ''
part_number: ''
size: 2_54_mm
type: socket
