classification: electronic
color: ''
description_extra: through_hole
description_main: 3x7_21_pin
id: electronic_header_2_54_mm_triple_row_3x7_21_pin_through_hole
manufacturer: ''
part_number: ''
size: 2_54_mm_triple_row
type: header
