classification: electronic
color: ''
description_extra: through_hole
description_main: 2_pin
id: electronic_header_2_5_mm_jst_xh_2_pin_through_hole
manufacturer: ''
part_number: ''
size: 2_5_mm_jst_xh
type: header
