classification: electronic
color: linear
description_extra: 2_5_volt
description_main: '1117'
id: electronic_pmic_sot_223_linear_1117_2_5_volt
manufacturer: ''
part_number: ''
size: sot_223
type: pmic
