classification: electronic
color: motor_driver
description_extra: ''
description_main: stepper_motor
id: electronic_breakout_board_step_stick_motor_driver_stepper_motor
manufacturer: ''
part_number: ''
size: step_stick
type: breakout_board
