classification: electronic
color: ''
description_extra: surface_mount_right_angle
description_main: 3_pin
id: electronic_header_1_mm_jst_sh_3_pin_surface_mount_right_angle
manufacturer: ''
part_number: ''
size: 1_mm_jst_sh
type: header
