classification: electronic
color: ''
description_extra: surface_mount_right_angle
description_main: 7_pin
id: electronic_header_2_5_mm_jst_xh_7_pin_surface_mount_right_angle
manufacturer: ''
part_number: ''
size: 2_5_mm_jst_xh
type: header
