classification: electronic
color: ''
description_extra: through_hole_right_angle
description_main: 4_pin
id: electronic_header_2_5_mm_jst_xh_4_pin_through_hole_right_angle
manufacturer: ''
part_number: ''
size: 2_5_mm_jst_xh
type: header
