classification: electronic
color: ''
description_extra: through_hole_short
description_main: 24_pin
id: electronic_header_2_54_mm_24_pin_through_hole_short
manufacturer: ''
part_number: ''
size: 2_54_mm
type: header
