classification: electronic
color: ''
description_extra: through_hole_right_angle
description_main: 2x40_80_pin
id: electronic_header_2_54_mm_dual_row_2x40_80_pin_through_hole_right_angle
manufacturer: ''
part_number: ''
size: 2_54_mm_dual_row
type: header
