classification: electronic
color: ''
description_extra: arduino_compatible
description_main: atmega328p
id: electronic_breakout_board_mcu_pro_mini_atmega328p_arduino_compatible
manufacturer: ''
part_number: ''
size: pro_mini
type: breakout_board_mcu
