classification: electronic
color: ''
description_extra: ''
description_main: 1000_ohm
id: electronic_resistor_quarter_watt_through_hole_1000_ohm
manufacturer: ''
part_number: ''
size: quarter_watt_through_hole
type: resistor
