classification: electronic
color: 3_pin_ground_pin_2
description_extra: ''
description_main: 8_mega_hertz
id: electronic_ceramic_resonator_3213_3_pin_ground_pin_2_8_mega_hertz
manufacturer: ''
part_number: ''
size: '3213'
type: ceramic_resonator
