classification: electronic
color: ''
description_extra: through_hole
description_main: 20_pin
id: electronic_socket_2_54_mm_20_pin_through_hole_dangerous_prototypes_raspberry_pi_pico_side_b
manufacturer: dangerous_prototypes
part_number: raspberry_pi_pico_side_b
size: 2_54_mm
type: socket
