classification: electronic
color: mcu
description_extra: ''
description_main: atmega328
id: electronic_ic_qfn_28_mcu_atmega328_microchip_atmega328p_mn
manufacturer: microchip
part_number: atmega328p_mn
size: qfn_28
type: ic
