classification: electronic
color: gray
description_extra: ''
description_main: 8_mm_length
id: electronic_crimp_bootlace_ferrule_1_mm_diameter_wire_gray_8_mm_length
manufacturer: ''
part_number: ''
size: 1_mm_diameter_wire
type: crimp_bootlace_ferrule
