classification: electronic
color: ''
description_extra: ''
description_main: 4_7_micro_farad
id: electronic_capacitor_0603_4_7_micro_farad
manufacturer: ''
part_number: ''
size: '0603'
type: capacitor
