classification: electronic
color: tantalum
description_extra: 16_volt
description_main: 4_7_micro_farad
id: electronic_capacitor_3216_avx_a_tantalum_4_7_micro_farad_16_volt
manufacturer: ''
part_number: ''
size: 3216_avx_a
type: capacitor
