classification: electronic
color: ''
description_extra: ''
description_main: 7500_ohm
id: electronic_resistor_quarter_watt_through_hole_7500_ohm
manufacturer: ''
part_number: ''
size: quarter_watt_through_hole
type: resistor
