classification: electronic
color: ''
description_extra: ''
description_main: raspberry_pi_2040
id: electronic_breakout_board_mcu_pico_raspberry_pi_2040
manufacturer: ''
part_number: ''
size: pico
type: breakout_board_mcu
