classification: electronic
color: ''
description_extra: ''
description_main: 2_pole_inline
id: electronic_connector_wago_221_2_pole_inline
manufacturer: ''
part_number: ''
size: wago_221
type: connector
