classification: electronic
color: ''
description_extra: surface_mount_right_angle
description_main: 2x16_32_pin
id: electronic_header_2_54_mm_dual_row_2x16_32_pin_surface_mount_right_angle
manufacturer: ''
part_number: ''
size: 2_54_mm_dual_row
type: header
