classification: electronic
color: ''
description_extra: package_marking_t4
description_main: ''
id: electronic_diode_sod_123_package_marking_t4_1n4148w
manufacturer: ''
part_number: 1n4148w
size: sod_123
type: diode
