classification: electronic
color: mcu
description_extra: arduino_compatible
description_main: atmega328p
id: electronic_breakout_board_pro_mini_mcu_atmega328p_arduino_compatible
manufacturer: ''
part_number: ''
size: pro_mini
type: breakout_board
