classification: electronic
color: ''
description_extra: ''
description_main: surface_mount_only
id: electronic_socket_usb_mini_surface_mount_only
manufacturer: ''
part_number: ''
size: usb_mini
type: socket
