classification: electronic
color: ''
description_extra: ''
description_main: ''
id: electronic_prototyping_breadboard_800_point
manufacturer: ''
part_number: ''
size: 800_point
type: prototyping_breadboard
