classification: electronic
color: brown
description_extra: ''
description_main: 8_mm_length
id: electronic_crimp_bootlace_ferrule_0_8_mm_diameter_wire_brown_8_mm_length
manufacturer: ''
part_number: ''
size: 0_8_mm_diameter_wire
type: crimp_bootlace_ferrule
