classification: electronic
color: ''
description_extra: ''
description_main: ''
id: electronic_breakout_board_servo_tester_32_mm_width_28_mm_height_hw_141
manufacturer: ''
part_number: hw_141
size: 32_mm_width_28_mm_height
type: breakout_board_servo_tester
