classification: electronic
color: i2c
description_extra: through_hole_right_angle
description_main: triple
id: electronic_header_oobb_i2c_triple_through_hole_right_angle
manufacturer: ''
part_number: ''
size: oobb
type: header
