classification: electronic
color: electrolytic
description_extra: 10_volt
description_main: 220_micro_farad
id: electronic_capacitor_8_mm_diameter_6_5_mm_tall_electrolytic_220_micro_farad_10_volt
manufacturer: ''
part_number: ''
size: 8_mm_diameter_6_5_mm_tall
type: capacitor
